export const product = {
  id: '11022836',
  name: 'Kimchi Fries',
  calories: 0,
  description: '',
  cost: 8.99,
  availability: {
    available: true,
    description: '',
  },
  minimumquantity: 1,
  maximumquantity: NaN,
  quantityincrement: 1,
  img: '/wp-content/uploads/2020/02/defaultproduct.png',
  modifiers: [
    {
      id: '1',
      description: 'Pick Your Korean BBQ',
      explanationtext: '',
      availability: {
        available: true,
        description: '',
      },
      supportschoicequantities: false,
      mandatory: true,
      maxaggregatequantity: Infinity,
      minaggregatequantity: 0,
      maxchoicequantity: 1,
      minchoicequantity: 1,
      minselects: 1,
      maxselects: 1,
      choicequantityincrement: 1,
      fractional: false,
      choices: [
        {
          id: '996341999',
          name: 'Spicy Pork',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Spicy Pork',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341998',
          name: 'Ribeye Beef',
          calories: 0,
          cost: 1,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Ribeye Beef',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996342002',
          name: 'Spicy Chicken',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Spicy Chicken',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996342000',
          name: 'Soy Glazed Chicken',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Soy Glazed Chicken',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996342001',
          name: 'Marinated Tofu',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Marinated Tofu',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
      ],
    },
    {
      id: '2',
      description: 'Pick Your Sauce',
      explanationtext: '',
      availability: {
        available: true,
        description: '',
      },
      supportschoicequantities: true,
      mandatory: false,
      maxaggregatequantity: 50,
      minaggregatequantity: 2,
      maxchoicequantity: 10,
      minchoicequantity: 2,
      minselects: 1,
      maxselects: 5,
      choicequantityincrement: 2,
      fractional: false,
      choices: [
        {
          id: '996341993',
          name: 'Magic Sauce',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Magic Sauce',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341992',
          name: 'Carrot Ginger Dressing',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Carrot Ginger Dressing',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341997',
          name: 'Kimchi Sauce',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Kimchi Sauce',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341995',
          name: 'Salsa Roja',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Salsa Roja',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341996',
          name: 'Sesame Vinaigrette',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Sesame Vinaigrette',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341991',
          name: 'Spicy Ranch',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Spicy Ranch',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341994',
          name: 'Sriracha',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Sriracha',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
      ],
    },
    {
      id: '3',
      description: 'Pick Your Hot Toppings',
      explanationtext: '',
      availability: {
        available: true,
        description: '',
      },
      supportschoicequantities: true,
      mandatory: false,
      maxaggregatequantity: 27,
      minaggregatequantity: 12,
      maxchoicequantity: 9,
      minchoicequantity: 6,
      minselects: 2,
      maxselects: 3,
      choicequantityincrement: 3,
      fractional: false,
      choices: [
        {
          id: '996341986',
          name: 'Bacon',
          calories: 0,
          cost: 1,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Bacon',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341981',
          name: 'Black Beans',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Black Beans',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341985',
          name: 'Brown Rice',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Brown Rice',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341989',
          name: 'Caramelized Kimchi',
          calories: 0,
          cost: 1,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Caramelized Kimchi',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341982',
          name: 'Fried Egg',
          calories: 0,
          cost: 1,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Fried Egg',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341984',
          name: 'Grilled Corn',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Grilled Corn',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341980',
          name: 'Grilled Mushrooms',
          calories: 0,
          cost: 0.5,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Grilled Mushrooms',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341983',
          name: 'Grilled Veggies',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Grilled Veggies',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341987',
          name: 'Jasmine Rice',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Jasmine Rice',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341990',
          name: 'Japchae Noodles',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Japchae Noodles',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341988',
          name: "Chi'Jeu Queso",
          calories: 0,
          cost: 1,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: "Chi'Jeu Queso",
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
      ],
    },
    {
      id: '4',
      description: 'Pick Your Cold Toppings',
      explanationtext: '',
      availability: {
        available: true,
        description: '',
      },
      supportschoicequantities: true,
      mandatory: false,
      maxaggregatequantity: 18,
      minaggregatequantity: 0,
      maxchoicequantity: 9,
      minchoicequantity: 3,
      minselects: 1,
      maxselects: 3,
      choicequantityincrement: 3,
      fractional: false,
      choices: [
        {
          id: '996341970',
          name: 'Avocado',
          calories: 0,
          cost: 2,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Avocado',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341966',
          name: 'Carrot',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Carrot',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341965',
          name: 'Monterey Jack Cheese',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Monterey Jack Cheese',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341976',
          name: 'Cilantro',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Cilantro',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341968',
          name: 'Kimchi',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Kimchi',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341973',
          name: 'Cucumber',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Cucumber',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341974',
          name: 'Guacamole',
          calories: 0,
          cost: 1,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Guacamole',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341972',
          name: 'Pickled Veggies',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Pickled Veggies',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341967',
          name: 'Shredded Lettuce/Cabbage',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Shredded Lettuce/Cabbage',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341969',
          name: 'Onion',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Onion',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341975',
          name: 'Red Cabbage',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Red Cabbage',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341977',
          name: 'Sesame Seeds',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Sesame Seeds',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341979',
          name: 'Spinach',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Spinach',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341978',
          name: 'Tortilla Strips',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Tortilla Strips',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
        {
          id: '996341971',
          name: 'Tomato',
          calories: 0,
          cost: 0,
          availability: {
            available: true,
            description: '',
          },
          isdefault: false,
          description: 'Tomato',
          img: '/wp-content/uploads/2019/12/option_food.png',
        },
      ],
    },
  ],
};
